server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:///${user.home}\Documents\git-local-repo
          search-locations: file:///${user.home}\Documents\test\git-local-repo
#        search-locations: file:///${user.home}\Documents\ git-local-repo
        git:
          uri: file:///${user.home}\Documents\ git-local-repo
#          uri: https://github.com/ksc036/spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

